name: Build docker
description: 'Build application with docker'
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
runs:
  using: composite
  steps:
    - name: Create docker image
      run: docker build . --file ./src/main/docker/Dockerfile.jvm --tag academy:$(date +%s)
      shell: bash