name: build
description: build
inputs:
  username:
    description: "dockerhub username"
  password:
    description: "dockerhub password"

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: docker push
      run: docker push ${{env.DOCKER_IMAGE_NAME}}
      shell: bash